title: Cyber Security Club @ Virginia Tech
subtitle: Hacking the planet since 2011
notice: Please bear with us as we migrate to this new site. Not everything is up yet.
email: officers@vtcsec.org
description: >
  Encouraging and expanding the study of cyber security and related fields.
  We aim to develop awareness and expertise in all areas of cyber security
  including physical, social, hardware, and software.
url: "http://vtcsec.org"
timezone: US/Eastern
edit_url: https://github.com/vtcsec/vtcsec.org/edit/gh-pages/

collections:
  meetings:
    output: true
defaults:
  - scope:
      path: ""
      type: meetings
    values:
      layout: meeting

# Build settings
markdown: kramdown
